### ISSUE TITLE
Document HitTestBezierContext

### ISSUE THREAD

**Issue by terryspitz** [wieslawsoltes/SpiroNet#12]
I'm interested in what it does: might be useful to me.

**Comment by wieslawsoltes** [comment]
It's used for hit-testing shapes.

Example usage: https://github.com/wieslawsoltes/SpiroNet/blob/c5f4effb99a7b698beba9eda36f3c3314645daf0/src/SpiroNet.Editor/Editor/SpiroEditor.cs#L593-L624

**Comment by wieslawsoltes** [comment]
@terryspitz Please note this code is ported to `C#` from https://github.com/fontforge/libspiro and is licensed under the `GPL-3.0`.

**Comment by terryspitz** [comment]
OK, it looks like it's for finding the closest knot (or curve segment) on the curve to a given point.  Thanks.
