### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by JoesCat** [wieslawsoltes/SpiroNet#6]
Hi @wieslawsoltes,
Please check Raph Levien's original spiro code, and please note that in addition to the GPL, there is also a patent grant that goes with the code (process flow). Please include the additional README file, https://github.com/fontforge/libspiro/blob/master/README-RaphLevien or something similar.
http://patents.justia.com/inventor/raphael-levien
This got my attention - https://github.com/fontforge/libspiro/issues/16

**Comment by wieslawsoltes** [comment]
@JoesCat Thanks for clarification, I was aware of patent grant and original licence. The original files contain original licence headers and project is licensed GPL-3.0 license. I have added README by Raph Levien to the root of the repository and added appropriate note in my README.

**Comment by JoesCat** [comment]
Thanks Wiesław,
Sometimes we look at these and we're not quite sure what to do with these 
sort of things, but later in time, you look back and think...
...you know what... ...it was the right thing to do  :-)

Hope you are enjoying the holiday season, and may you have a Happy New 
Year!

Cheers,
Joe
