### ISSUE TITLE
Incorrect links to ZIP and TAR at SpiroNet page

### ISSUE THREAD

**Issue by KvanTTT** [wieslawsoltes/SpiroNet#7]
They point on https://github.com/wieslawsoltes/SpiroNet/zipball/gh-pages instead of AppVeyor artifacts as I guess.

**Comment by wieslawsoltes** [comment]
The links on http://wieslawsoltes.github.io/SpiroNet/ are autogenarated by GitHub page template. Don't know how to change them.
